version: '3'
services:
  redis:
    image: redis:latest
    hostname: redis
    volumes:
      - ./host_volume/redis:/data
    networks:
      - mynet123
  messenger:
    image: vivekbhandari/messenger
    hostname: messenger
    volumes:
      - ./:/opt/messenger
    depends_on: 
      - redis
    ports:
      - "3000:3000"
      - "8080:8080"
    restart: on-failure
    networks: 
      - mynet123
networks:
    mynet123:
        driver: bridge
      
